{% set name = "pythonfinder" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pythonfinder-{{ version }}.tar.gz
  sha256: 6944a1bfc693c09ec48c6881519b2d6e435bc6c1d1b8389277efeeec43f5edad

build:
  number: 0
  skip: true  # [py==30 or py==31 or py==32 or py==33]
  entry_points:
    - pyfinder = pythonfinder.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=41.0
  run:
    - attrs
    - backports.functools_lru_cache  # [py==27]
    - cached-property
    - click
    - packaging
    - pathlib2  # [py<35]
    - python
    - six

test:
  imports:
    - pythonfinder
    - pythonfinder._vendor
  commands:
    - pip check
    - pyfinder --help
  requires:
    - pip

about:
  home: https://github.com/sarugaku/pythonfinder
  summary: A cross-platform python discovery tool to help locate python on any system.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
