context:
  name: pythonfinder
  version: 1.3.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/pythonfinder-${{ version }}.tar.gz
  sha256: d1c88d048d48736a198c74bd6f3dddf48361e7e2cdee01a9dddc7a952b63aa43

build:
  number: 3
  skip: match(python, "==3.0") or match(python, "==3.1") or match(python, "==3.2") or match(python, "==3.3")
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - pyfinder = pythonfinder.cli:cli

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
  host:
    - pip
    - python
    - setuptools >=41.0
    - packaging 21.3.*
  run:
    - attrs
    - if: match(python, "==2.7")
      then: backports.functools_lru_cache
    - cached-property
    - click
    - packaging 21.3.*
    - if: match(python, "<3.5")
      then: pathlib2
    - python
    - six

tests:
  - python:
      imports:
        - pythonfinder
        - pythonfinder._vendor
  - requirements:
      run:
        - pip
    script:
      - pip check
      - pyfinder --help

about:
  summary: A cross-platform python discovery tool to help locate python on any system.
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/sarugaku/pythonfinder

extra:
  recipe-maintainers:
    - hadim
